### ISSUE TITLE
Keeping track of the purchase process 

### ISSUE THREAD

**Issue by DooorisXu** [MLavrentyev/TeamManager#28]
Adding two other columns to keep track of the purchase process -- Order Status & Delivery Status.  

This is how I am picturing it: Next to approval status, there are these two columns Order Status and Delivery Status.  In terms of response, they are both in the format of "check (yes)/question mark(pending)/cross (no)", similar to approval status.  So the finance person will click on this entry and then check this column once she placed the order and then check the other column after the product is delivered.  

This is second on our priority list.

**Comment by MLavrentyev** [comment]
Should be all set as of e1a783062382b6abf23c5c9f0d91297f51233d71. If you find any new bugs, open a new issue and I'll look into it.
