### ISSUE TITLE
Summary page (w/ running balance)

### ISSUE THREAD

**Issue by DooorisXu** [MLavrentyev/TeamManager#32]
TBD

**Comment by DooorisXu** [comment]
First, great work on the email viewer group!  Way to go! 
Re sumary page: Please hold tight.  I am reaching out to our finance person to decide the functionality & layout she is picturing for this.  I will get back to you by the end of today.

**Comment by DooorisXu** [comment]
The summary sounds good.  And I think we can merge the summar and the export to keep it neat.  Instead of having export on the top, perhaps we can make it a button on the summary page and call it "Export full inventory" or something similar.

**Comment by MLavrentyev** [comment]
@DooorisXu what exact info do you want shown on the summary page?

**Comment by MLavrentyev** [comment]
This is what I was thinking the site could look like:

![site](https://user-images.githubusercontent.com/12854315/51093822-63884c00-1775-11e9-9805-f60662eef3c7.PNG)

The chart could be made using [Chart.js](https://www.chartjs.org/docs/latest/) and the bottom would have stats on the left for the team and on the right for you. Also will have export button somewhere.

**Comment by DooorisXu** [comment]
The original idea was to keep a running balance of the amount of money we have left, but then it got vetoed by the finance ppl because of so many things that will potentially cause discrepancy between this and QuickBooks.  As for the summary page, I showed this to the team and they liked the idea of keeping the monthly expense and the graph you have.

**Comment by MLavrentyev** [comment]
Cool! I'll get started working on it.

**Comment by MLavrentyev** [comment]
@DooorisXu let me know what you think of this and if you want anything else:
![site](https://user-images.githubusercontent.com/12854315/51226815-31b2e900-191f-11e9-8de2-b51e207b1d68.PNG)

I'm going to add the export button tomorrow as well as fix a bug or two on the date range stuff (seems to be off by a day or something)

**Comment by DooorisXu** [comment]
The page looks really good.  A couple of questions: 1. are the dots interactive? For example, does it show the values when you put the cursor on it? 2. Is it possible to add more options for the vertical axis (an example: amount spent on purchases)?

**Comment by DooorisXu** [comment]
Overall, good work!

**Comment by MLavrentyev** [comment]
1. Yes, they are (albeit the tooltips are kinda ugly, I'm working on it)
2. I'll add a second axis on the right that shows $ approved

**Comment by MLavrentyev** [comment]
This is what I've got: [![Screenshot from Gyazo](https://gyazo.com/c802314150c1051ae58d364f7e5b0819/raw)](https://gyazo.com/c802314150c1051ae58d364f7e5b0819)

I'm going to push it to production as-is and continue working on it. Note that if people have any feedback on looks or find a bug, have them submit an issue.
