### ISSUE TITLE
Including the shipping cost

### ISSUE THREAD

**Issue by DooorisXu** [MLavrentyev/TeamManager#33]
Django only keeps records of the product price and the total cost but overlooks the shipping cost.  
Possible resolutions:
1. Making Grace an admin and making her add the shipping cost/number of units to the unit price after each purchase
2. Adding a space in the request that allows her to add the shipping cost after the order is placed 
3. Alternative?

**Comment by MLavrentyev** [comment]
I'm going to integrate option 2 in - it can be another field at some point. I'm going to implement this the following way: in the buttons that will be added in #28 on the detail page to indicate ordered or delivered, on the "ordered" part, there will be an option to add a shipping cost.

**Comment by MLavrentyev** [comment]
Done (see #28)
