### ISSUE TITLE
Add a message in the email & page

### ISSUE THREAD

**Issue by DooorisXu** [MLavrentyev/TeamManager#37]
Adding this message to the email sent to approvers (italic, blue):
If this product is not from AndyMark or Vex, please place the order on your own after approving it.

Displaying this message on the home page:
"Approvers, please place the order on your own if the product is not from AndyMark or Vex"

**Comment by MLavrentyev** [comment]
Totally can & will do (once I have time ahhh) for the email. As for the display on the page - I'm not totally sure this would be the best way to go about it. I think this project is best kept general (i.e. can be applied to things other than FRC as well), so I'll keep thinking on a way to implement it through some sort of config file, etc. If you have any ideas on that front, totally let me know.

**Comment by DooorisXu** [comment]
Re email-template: Thanks!
Re webpage & config file: I agree.  I do not have a good solution rn but I will keep thinking about it.
